/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SummarizerIndexRouteImport } from './routes/summarizer/index'
import { Route as PortfolioChatIndexRouteImport } from './routes/portfolio-chat/index'
import { Route as CodeExplainerIndexRouteImport } from './routes/code-explainer/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SummarizerIndexRoute = SummarizerIndexRouteImport.update({
  id: '/summarizer/',
  path: '/summarizer/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioChatIndexRoute = PortfolioChatIndexRouteImport.update({
  id: '/portfolio-chat/',
  path: '/portfolio-chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeExplainerIndexRoute = CodeExplainerIndexRouteImport.update({
  id: '/code-explainer/',
  path: '/code-explainer/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/code-explainer/': typeof CodeExplainerIndexRoute
  '/portfolio-chat/': typeof PortfolioChatIndexRoute
  '/summarizer/': typeof SummarizerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/code-explainer': typeof CodeExplainerIndexRoute
  '/portfolio-chat': typeof PortfolioChatIndexRoute
  '/summarizer': typeof SummarizerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/code-explainer/': typeof CodeExplainerIndexRoute
  '/portfolio-chat/': typeof PortfolioChatIndexRoute
  '/summarizer/': typeof SummarizerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/code-explainer/' | '/portfolio-chat/' | '/summarizer/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/code-explainer' | '/portfolio-chat' | '/summarizer'
  id:
    | '__root__'
    | '/'
    | '/code-explainer/'
    | '/portfolio-chat/'
    | '/summarizer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodeExplainerIndexRoute: typeof CodeExplainerIndexRoute
  PortfolioChatIndexRoute: typeof PortfolioChatIndexRoute
  SummarizerIndexRoute: typeof SummarizerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summarizer/': {
      id: '/summarizer/'
      path: '/summarizer'
      fullPath: '/summarizer/'
      preLoaderRoute: typeof SummarizerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio-chat/': {
      id: '/portfolio-chat/'
      path: '/portfolio-chat'
      fullPath: '/portfolio-chat/'
      preLoaderRoute: typeof PortfolioChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-explainer/': {
      id: '/code-explainer/'
      path: '/code-explainer'
      fullPath: '/code-explainer/'
      preLoaderRoute: typeof CodeExplainerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodeExplainerIndexRoute: CodeExplainerIndexRoute,
  PortfolioChatIndexRoute: PortfolioChatIndexRoute,
  SummarizerIndexRoute: SummarizerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
